export default [{
  id: 0,
  label: '系统管理',
  url: '',
  icon: 'gear-b',
  type: 'MODULE'
}, {
  id: 1,
  parentId: 0,
  label: '用户管理',
  url: '/system/account',
  icon: '',
  type: 'PAGE'
}, {
  id: 2,
  label: '基础信息',
  url: '',
  icon: 'document-text',
  type: 'MODULE'
}, {
  id: 3,
  parentId: 2,
  label: '商品列表',
  url: '/base/product',
  icon: 'document-text',
  type: 'MODULE'
}, {
  id: 4,
  label: '业务办理',
  url: '',
  icon: 'ios-compose',
  type: 'PAGE'
}, {
  id: 5,
  label: '入库管理',
  parentId: 4,
  url: '/manage/enterStock',
  icon: '',
  type: 'PAGE'
}, {
  id: 6,
  label: '入库单',
  parentId: 5,
  url: '/manage/enterStockDetail',
  icon: '',
  type: 'PAGE',
  noMenu: true
}, {
  id: 7,
  label: '入库单',
  parentId: 5,
  url: '/manage/enterStockDetail/:id',
  icon: '',
  type: 'PAGE',
  noMenu: true
}, {
  id: 8,
  label: '出库管理',
  parentId: 4,
  url: '/manage/deliveryStock',
  icon: '',
  type: 'PAGE'
}, {
  id: 9,
  label: '出库单',
  parentId: 8,
  url: '/manage/deliveryStockDetail',
  icon: '',
  type: 'PAGE',
  noMenu: true
}, {
  id: 10,
  label: '出库单',
  parentId: 8,
  url: '/manage/deliveryStockDetail/:id',
  icon: '',
  type: 'PAGE',
  noMenu: true
}, {
  id: 11,
  parentId: 0,
  label: '修改密码',
  url: '/system/changePassword',
  icon: '',
  type: 'PAGE',
  noMenu: true
}]
